name: Monthly Corporate Sync

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  sync_data:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          "C:\Users\lance_j\AppData\Local\Programs\Python\Python313\python.exe" -m pip install --upgrade pip
          "C:\Users\lance_j\AppData\Local\Programs\Python\Python313\python.exe" -m pip install -r requirements.txt

      - name: Run Sync Script
        env:
          DB_URL: ${{ secrets.DB_URL }}
        run: "C:\Users\lance_j\AppData\Local\Programs\Python\Python313\python.exe" script.py